[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
lineLength = 80
ignore = [
            "E501", # line too long
          ] 

[language-server.ruff.config.settings.lint]
select = ["E4", "E7"]
preview = false

[language-server.ruff.config.settings.format]
preview = true


# [language.formatter]
# command = "black"
# args = ["--line-length", "100", "--quiet", "-"]
